# k create ns project-hamster
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: project-hamster
spec: {}
status: {}
---
# k -n project-hamster create sa processor
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: processor
---
# k -n project-hamster create role processor --verb=create --resource=secret,configmap
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: processor
  namespace: project-hamster
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - create
---
# k -n project-hamster create rolebinding processor --role=processor --serviceaccount=project-hamster:processor
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: processor
  namespace: project-hamster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: processor
subjects:
- kind: ServiceAccount
  name: processor
  namespace: project-hamster
